version: '3.7'

services:

  node-ps5-actor:
    container_name: node-ps5-actor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5454:5454
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
