version: '3.7'

services:

  node-video-select:
    container_name: node-video-select
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3131:3131
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
